name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0   # full history

      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs fetch --all
          git lfs checkout

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add space https://pankajkumar90:${HF_TOKEN}@huggingface.co/spaces/pankajkumar90/pneumonia-detection-api
          git push space main --force
